name: Build Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  DATABASE_URL: "http://localhost:3000"
  BASE_URL: "http://localhost:3000"
  API_URL: "http://localhost:3000"
  NEXT_PUBLIC_API_URL: "http://localhost:3000"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
